/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.sdccd.mesa.cisc190.practice5.client;

public class Main {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
