/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.sdccd.mesa.cisc190.practice5.server;


import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

public class MainTest {
    @Test
    public void testMain() {
    }
}
